apiVersion: v1
kind: Pod
metadata:
  name: ctstraffic-reciever
spec:
  hostNetwork: true
  nodeSelector: 
    kubernetes.io/os: windows
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
  containers:
    - name: ctstraffic-container
      image: ueqt/ctstraffic:latest
      imagePullPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: ctstraffic-sender
spec:
  nodeSelector: 
    kubernetes.io/os: windows
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
  containers:
    - name: ctstraffic-container
      image: ueqt/ctstraffic:latest
      imagePullPolicy: Always
