apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linuxonce-pvc
spec:
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: linuxonce-pod
spec:
  nodeSelector:
    "beta.kubernetes.io/os": linux
  volumes:
    - name: linuxonce-pv
      persistentVolumeClaim:
        claimName: linuxonce-pvc
  containers:
    - name: linuxonce-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/data"
          name: linuxonce-pv