apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-csi
provisioner: smb.csi.akshci.com
parameters:
   source: \\mgmt.corp.contoso.com\share
   csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
   csi.storage.k8s.io/node-stage-secret-namespace: "default"
   createSubDir: "false"  # optional: create a sub dir for new volume
reclaimPolicy: Retain  # only Retain is supported
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: linuxmany-pvc
spec:
  storageClassName: smb-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: linuxmany-pod1
spec:
  nodeSelector:
    "beta.kubernetes.io/os": linux
  volumes:
    - name: linuxmany-pv1
      persistentVolumeClaim:
        claimName: linuxmany-pvc
  containers:
    - name: linuxmany-container
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: linuxmany-pv1
---
apiVersion: v1
kind: Pod
metadata:
  name: linuxmany-pod2
spec:
  nodeSelector:
    "beta.kubernetes.io/os": linux
  volumes:
    - name:  linuxmany-pv2
      persistentVolumeClaim:
        claimName: linuxmany-pvc
  containers:
    - name: task-pv-container2
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name:  linuxmany-pv2
