apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-csi
provisioner: smb.csi.akshci.com
parameters:
   source: \\mgmt\share
   csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
   csi.storage.k8s.io/node-stage-secret-namespace: "default"
   createSubDir: "false"  # optional: create a sub dir for new volume
reclaimPolicy: Retain  # only Retain is supported
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: windowsmany-pvc
spec:
  storageClassName: smb-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: windowsmany-pod1
spec:
  nodeSelector:
    "beta.kubernetes.io/os": windows
  volumes:
    - name: windowsmany-pv1
      persistentVolumeClaim:
        claimName: windowsmany-pvc
  containers:
    - name: windowsmany-container
      image: e2eteam/busybox:1.29
      command:
        - "powershell.exe"
        - "-Command"
        - "while (1) { Add-Content -Encoding Ascii C:\\sc\\smb\\data.txt $(Get-Date -Format u); sleep 1 }"
      volumeMounts:
        - mountPath: "/data"
          name: windowsmany-pv1
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: windowsmany-pod2
spec:
  nodeSelector:
    "beta.kubernetes.io/os": windows
  volumes:
    - name:  windowsmany-pv2
      persistentVolumeClaim:
        claimName: windowsmany-pvc
  containers:
    - name: task-pv-container2
      image: e2eteam/busybox:1.29
      command:
        - "powershell.exe"
        - "-Command"
        - "while (1) { Add-Content -Encoding Ascii C:\\sc\\smb\\data.txt $(Get-Date -Format u); sleep 1 }"
      volumeMounts:
        - mountPath: "/data"
          name:  windowsmany-pv2
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
