apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: windowsonce-pvc
spec:
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
   storage: 10Gi
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  labels: 
    app: win-webserver 
  name: win-webserver 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: win-webserver 
  template: 
    metadata: 
      labels: 
        app: win-webserver 
      name: win-webserver 
    spec: 
      containers: 
        - name: windowswebserver 
          image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019 
          ports:  
            - containerPort: 80    
          volumeMounts: 
            - name: windowsonce-pv 
              mountPath: "/mnt/akshciscsi" 
      volumes: 
        - name: windowsonce-pv 
          persistentVolumeClaim: 
            claimName:  windowsonce-pvc 
      nodeSelector: 
        kubernetes.io/os: windows
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "windows"
          effect: "NoSchedule"