$appId ='<Your Azure service principal name>'
$password ='<Your Azure service principal password>'
$tenant ='<Your Azure tenant ID>'
$appClonedRepo ='<The URL for the "Hello Arc" cloned GitHub repository>'
$subscriptionId ='<Your subscription ID>'